- name: create kube-verify deployment  
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kube-verify
        namespace: kube-verify
        labels:
          app: kube-verify
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: kube-verify
        template:
          metadata:
            labels:
              app: kube-verify
          spec:
            containers:
            - name: nginx
              image: quay.io/clcollins/kube-verify:01
              ports:
              - name: http
                containerPort: 8080
