- name: Create kube-verify ingress
  k8s:
    state: present
    definition:
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: kube-verify-ingress
        namespace: kube-verify
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/rewrite-target: /
      spec:
        rules:
        - host: kube-verify.local
          http:
            paths:
            - path: /
              # pathType: Prefix
              backend:
                serviceName: kube-verify
                servicePort: 80
