- name: Run Namespace tasks
  import_tasks: namespaces.yml

- name: Setup MetalLB
  import_tasks: metallb.yml

- name: Run Deployment tasks
  import_tasks: deployments.yml

- name: Run Service tasks
  import_tasks: services.yml

# - name: Run Ingress tasks
#   import_tasks: ingress.yml


