##
# - name: Install cert-manager                                                                                                                                                                                       
#   k8s:                                                                                                                                                                                                             
#     definition: '{{ item }}'                                                                                                                                                                                       
#     namespace: cert-manager                                                                                                                                                                                        
#   with_items: '{{ lookup("url", "https://github.com/jetstack/cert-manager/releases/download/v0.10.1/cert-manager.yaml", split_lines=False) | from_yaml_all | list }}'                                              
#   when: item is not none



# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/namespace.yaml
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/metallb.yaml
# # On first install only
# kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

- name: install metallb manifest
  community.kubernetes.k8s:
    definition: '{{ item }}'
    namespace: metallb-system
  with_items: '{{ lookup("url", "https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml", split_lines=False) | from_yaml_all | list }}'
  when: item is not none

# - name: Create secret for metallb
#   community.kubernetes.k8s:
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: memberlist
#         namespace: metallb-system
#       type: Opaque
#       data:

- name: Create config map for address pool
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config
        namespace: metallb-system
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
              - 192.168.10.1-192.168.10.254

# # kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/baremetal/deploy.yaml
# - name: Install ingress-nginx
#   community.kubernetes.k8s:
#     definition: '{{item}}'
#     namespace: ingress-nginx
#   with_items: '{{ lookup("url", "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.43.0/deploy/static/provider/baremetal/deploy.yaml", split_lines=False) | from_yaml_all | list }}'
#   when: item is not none