- name: create kube-verify service
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: kube-verify
        namespace: kube-verify
      spec:
        type: LoadBalancer
        selector:
          app: kube-verify
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 8080
        externalTrafficPolicy: Local


