- name: create kube-verify service
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx
        namespace: default
      spec:
        type: LoadBalancer
        selector:
          app: nginx
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 80


