---
- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: common

- hosts: servers
  become: yes
  roles:
    - role: server

- hosts: agents
  become: yes
  roles:
    - role: agent