---
- hosts: all
  remote_user: pi
  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
      become: yes

    - name: Install necessary packages
      apt:
        pkg:
        - python-apt

    - name: Check CPU temp
      command: /opt/vc/bin/vcgencmd measure_temp
      register: cpu_temp
      become: yes

    - name: print CPU Temp
      debug: 
        msg: "{{cpu_temp.stdout}}"


