- name: Set authorized key taken from file
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Remove unneeded dependencies
  apt:
    autoremove: yes

- name: Check if restart required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: r
  changed_when: r.stat.exists
  notify:
    - Reboot pi

# - name: Install necessary packages
#   apt:
#     pkg:
#     - python-apt
#   notify:
#     - Reboot pi

# - name:

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
# # - name: print CPU Temp
# #   debug:
# #     msg: "{{cpu_temp.stdout}}"

