- name: Set authorized key taken from file
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install necessary packages
  apt:
    pkg:
    - python-apt

- name: Check CPU temp
  command: /opt/vc/bin/vcgencmd measure_temp
  register: cpu_temp

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: print CPU Temp
  debug: 
    msg: "{{cpu_temp.stdout}}"


